#!/bin/bash

function send_slack () {
    [ -z "$SLACK_URL" ] && eecho "Unable to send slack because SLACK_URL variable is empty!"
    FORMATED_MESSAGE="$(echo "$1" | sed 's/"/\\"/g' | sed "s/'/\\'/g" )"
    curl -s -X POST $SLACK_URL -H 'Content-type: application/json' --data '{"text":"'"$(hostname): $SCRIPT_NAME: $FORMATED_MESSAGE"'"}' >/dev/null
}
